enum ScreenNameEnum {
  //Auth Screens
  SPLASH_SCREEN = 'SPLASH_SCREEN',
  WELLCOME_SCREEN = 'WELLCOME_SCREEN',
  LOGIN_SCREEN = 'LOGIN_SCREEN',
  SIGNUP_SCREEN = 'SIGNUP_SCREEN',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  SENT_OTP ='SENT_OTP',
  OTP_SCREEN = 'OTP_SCREEN',
  LOGIN_OPTION ='LOGIN_OPTION',

//tab 
  BOTTOM_TAB = 'BOTTOM_TAB',
  HOME_SCREEN ="HOME_SCREEN",
  SEARCH_SCREEN = 'SEARCH_SCREEN',
  BOOKING_SCREEN = 'BOOKING_SCREEN',
  PROFILE_SCREEN = 'PROFILE_SCREEN',


  CHAT_SCREEN = 'CHAT_SCREEN',
  CHAT_CONTACT_SCREEN = 'CHAT_CONTACT_SCREEN',
//Profile Section

  EDIT_PROFILE = 'EDIT_PROFILE',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  WISHLIST_SCREEN ='WISHLIST_SCREEN',
  BOOKING_TAB ='BOOKING_TAB',
  SUBSCRIPTION_SCREEN='SUBSCRIPTION_SCREEN',
  NOTIFICATION_SCREEN = 'NOTIFICATION_SCREEN',
  PRIVACY_POLICY = 'PRIVACY_POLICY',
  TERM_CONDITION ='TERM_CONDITION',

 // Featurs

 PLACE_DETAILS ='PLACE_DETAILS',
 BOOKING_DETAILS ='BOOKING_DETAILS',
 TRAVELER_DETAILS = 'TRAVELER_DETAILS',
 PAYMENT_DETAILS = 'PAYMENT_DETAILS',
 PAYMENT_SUCCESS ='PAYMENT_SUCCESS',
 
  //company
  ADD_PROPERTY ='ADD_PROPERTY',
  CompanyBooking='CompanyBooking',
  CProfile ='CProfile',
  CbookingDetails='CbookingDetails',

// chat







 


}

export default ScreenNameEnum;
